### ISSUE TITLE
Crash decoding a VQ PVR texture

### ISSUE THREAD

**Issue by PiKeyAr** [nickworonekin/puyotools#26]
Hello, and thank you for making this tool. I've been using it for years myself, and many Sonic Adventure (+DX) hacking tools also use it as a dependency.

A while ago we found an issue with VQ textures and I thought I should post it here.
[E_SAI.zip](https://github.com/nickworonekin/puyotools/files/4844559/E_SAI.zip)
Attached is a PVM from Sonic Adventure (Dreamcast). Opening it in Archive Explorer and clicking on the first texture causes the program to crash with the following error. Do you think this can be fixed?

```
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at VrSharp.PvrTexture.PvrDataCodec.SmallVq.Decode(Byte[] source, Int32 sourceIndex, Int32 width, Int32 height)
   at VrSharp.VrTexture.DecodeTexture()
   at VrSharp.VrTexture.ToBitmap()
   at VrSharp.VrTexture.Save(Stream destination)
   at PuyoTools.Modules.Texture.TextureBase.Read(Stream source)
   at PuyoTools.GUI.TextureViewer.OpenTexture(Stream data, String fname, TextureFormat format)
   at PuyoTools.GUI.ArchiveExplorer.OpenTexture(Stream data, String fname, TextureFormat format)
   at PuyoTools.GUI.ArchiveExplorer.listView_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
I have more crashing PVMs if you need more test cases.

**Comment by nickworonekin** [comment]
Didn't realize Small VQ and Small VQ with Mipmaps PVR textures for 32x32 and 64x64 ones didn't use the same number of palette entries.

**Comment by PiKeyAr** [comment]
Thank you for getting back to me and fixing the issue so quickly! I've built and tested the new version on all problematic textures I could find, and the tool decoded them fine.
